import { AuditLogModel } from '../../src/infrastructure/database/models/AuditLogModel.js';
import { TipModel } from '../../src/infrastructure/database/models/TipModel.js';
import { MongoTipRepository } from '../../src/infrastructure/adapters/outbound/persistence/MongoTipRepository.js';
import { randomUUID } from 'node:crypto';
import { describe, it, beforeAll, afterAll, expect, vi } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import { LEGAL_ACCEPTANCE_VERSION } from '@ubuntu-fund/types';
import { createTestApp } from '../helpers/testApp.js';
import { connectTestDatabase, dropTestDatabase, disconnectTestDatabase } from '../helpers/testDatabase.js';
import { UserModel } from '../../src/infrastructure/database/models/UserModel.js';
import { ProfileModel } from '../../src/infrastructure/database/models/ProfileModel.js';
import { PushTokenModel } from '../../src/infrastructure/database/models/PushTokenModel.js';
import { NewsletterSubscriptionModel } from '../../src/infrastructure/database/models/NewsletterSubscriptionModel.js';
import { WalletModel } from '../../src/infrastructure/database/models/WalletModel.js';
import { DonationModel } from '../../src/infrastructure/database/models/DonationModel.js';
import { ActivityAlertPreferenceModel } from '../../src/infrastructure/database/models/ActivityAlertPreferenceModel.js';
import { CreatorProfileModel } from '../../src/infrastructure/database/models/CreatorProfileModel.js';
import { AccountDeletionRequestModel } from '../../src/infrastructure/database/models/AccountDeletionRequestModel.js';
import { MongoAccountErasure } from '../../src/infrastructure/adapters/outbound/persistence/MongoAccountErasure.js';

describe('Account erasure and retained-record review', () => {
  let app: Express;
  beforeAll(async () => { await connectTestDatabase(); app = await createTestApp(); });
  afterAll(async () => { await dropTestDatabase(); await disconnectTestDatabase(); });
  async function register() {
    const email = `erase-${randomUUID()}@example.com`;
    const result = await request(app).post('/api/v1/auth/register').send({ email, password: 'SecurePass123', name: 'Erase Test', legalAcceptance: { version: LEGAL_ACCEPTANCE_VERSION, acceptedTerms: true, ageConfirmed: true } }).expect(201);
    return { ...result.body.data, email, bearer: `Bearer ${result.body.data.tokens.accessToken}` };
  }
  it('removes operational data, preserves money and queues residual-data review', async () => {
    const account = await register();
    const id = account.user.id;
    await ProfileModel.create({ userId: id, phone: '0200000000', bio: 'Private profile' });
    await PushTokenModel.create({ userId: id, token: `ExponentPushToken[${id}]`, platform: 'ios' });
    await NewsletterSubscriptionModel.create({ email: account.email });
    await CreatorProfileModel.create({ userId: id, handle: `erase-${id}`, displayName: 'Creator', bio: 'Private creator bio' });
    await WalletModel.updateOne({ userId: id }, { $set: { balance: 150 } });
    const tip = await TipModel.create({ creatorUserId: 'creator', supporterUserId: id, amount: 25, currency: 'GHS', providerRef: `tip-${randomUUID()}`, requestFingerprint: 'private-fingerprint', publicContentFingerprint: 'review-fingerprint', publicReviewNotes: 'Review notes containing personal context', checkout: { checkoutUrl: 'https://private.test', accessCode: 'private' } });
    const donation = await DonationModel.create({ donorId: id, campaignId: '507f1f77bcf86cd799439011', amount: 25, currency: 'GHS', isAnonymous: false });
    await ActivityAlertPreferenceModel.create({ userId: id, choices: { donationsSent_email: { enabled: true, enabledAt: new Date(), changedAt: new Date() } } });
    await request(app).delete('/api/v1/profile').set('Authorization', account.bearer).expect(200);
    expect(await ProfileModel.countDocuments({ userId: id })).toBe(0);
    expect(await PushTokenModel.countDocuments({ userId: id })).toBe(0);
    expect(await NewsletterSubscriptionModel.countDocuments({ email: account.email })).toBe(0);
    expect(await CreatorProfileModel.countDocuments({ userId: id })).toBe(0);
    expect((await WalletModel.findOne({ userId: id }))?.balance).toBe(150);
    const retainedTip = await TipModel.findById(tip.id);
    expect(retainedTip).toMatchObject({ amount: 25, currency: 'GHS', providerRef: tip.providerRef, isAnonymous: true });
    expect(retainedTip?.checkout?.checkoutUrl).toBeUndefined();
    expect(retainedTip?.requestFingerprint).toBeUndefined();
    expect(retainedTip?.publicContentFingerprint).toBeUndefined();
    expect(retainedTip?.publicReviewNotes).toBeUndefined();
    expect(retainedTip?.checkoutRevokedAt).toBeInstanceOf(Date);
    expect(await new MongoTipRepository().saveCheckout(tip.providerRef, { checkoutUrl: 'https://late.test', accessCode: 'late' })).toBe(false);
    const retainedDonation = await DonationModel.findById(donation._id);
    expect(retainedDonation).toMatchObject({ donorId: id, campaignId: donation.campaignId, amount: 25, currency: 'GHS', isAnonymous: true });
    expect(await ActivityAlertPreferenceModel.countDocuments({ userId: id })).toBe(0);
    const deleted = await UserModel.findById(id);
    expect(deleted?.email).toBe(`deleted-${id}@invalid.ujimora`);
    expect(deleted?.name).toBe('Deleted user');
    expect(deleted?.deletedAt).toBeDefined();
    const review = await AccountDeletionRequestModel.findOne({ userId: id });
    expect(review?.status).toBe('review_required');
    expect(review?.contactEmail).toBe(account.email);
    expect(review?.nextReviewAt).toBeDefined();
    await request(app).get('/api/v1/profile').set('Authorization', account.bearer).expect(401);
  });
  it('survives partial cleanup failure and supports retry from a new worker', async () => {
    const account = await register();
    await ProfileModel.create({ userId: account.user.id, bio: 'Retry me' });
    const failure = vi.spyOn(ProfileModel, 'deleteMany').mockImplementationOnce(() => { throw new Error('Temporary cleanup failure'); });
    await request(app).delete('/api/v1/profile').set('Authorization', account.bearer).expect(200);
    failure.mockRestore();
    expect((await AccountDeletionRequestModel.findOne({ userId: account.user.id }))?.status).toBe('pending');
    const nextReviewAt = new Date(Date.now() + 14 * 86400000);
    await AccountDeletionRequestModel.updateOne({ userId: account.user.id }, { $set: { revision: 2, reviewNotes: 'Follow up on retained records after cleanup.', nextReviewAt } });
    expect(await new MongoAccountErasure().sweepPending()).toBe(1);
    expect(await AccountDeletionRequestModel.findOne({ userId: account.user.id })).toMatchObject({ revision: 3, reviewNotes: 'Follow up on retained records after cleanup.', nextReviewAt, status: 'review_required' });
    expect(await new MongoAccountErasure().sweepPending()).toBe(0);
    expect((await AccountDeletionRequestModel.findOne({ userId: account.user.id }))?.revision).toBe(3);
    expect(await ProfileModel.countDocuments({ userId: account.user.id })).toBe(0);
  });
  it('prevents concurrent retention reviews from overwriting notes and rolls back failed audit writes', async () => {
    const staff = await register();
    await UserModel.updateOne({ _id: staff.user.id }, { $set: { role: 'admin' } });
    const item = await AccountDeletionRequestModel.create({ userId: randomUUID(), contactEmail: 'fixture@example.com', nextReviewAt: new Date(Date.now() + 86400000) });
    const input = { revision: 0, reviewNotes: 'Reviewed processor follow-up and retained financial records.', nextReviewAt: new Date(Date.now() + 172800000).toISOString() };
    const review = () => request(app).put(`/api/v1/admin/privacy-requests/${item.id}/review`).set('Authorization', staff.bearer).send(input);
    const audit = vi.spyOn(AuditLogModel, 'create').mockRejectedValueOnce(new Error('Audit unavailable'));
    try { await review().expect(500); } finally { audit.mockRestore(); }
    expect(await AccountDeletionRequestModel.findById(item.id)).toMatchObject({ revision: 0, reviewNotes: '' });
    const results = await Promise.all([review(), review()]);
    expect(results.map(result => result.status).sort()).toEqual([200, 409]);
    expect(await AccountDeletionRequestModel.findById(item.id)).toMatchObject({ revision: 1, reviewNotes: input.reviewNotes });
    expect(await AuditLogModel.countDocuments({ resource: item.id, action: 'privacy.retention_review' })).toBe(1);
  });
  it('restricts the review queue to current admins and rejects stale admin tokens after demotion', async () => {
    const account = await register();
    await request(app).get('/api/v1/admin/privacy-requests').expect(401);
    await request(app).get('/api/v1/admin/privacy-requests').set('Authorization', account.bearer).expect(403);
    await UserModel.updateOne({ _id: account.user.id }, { $set: { role: 'admin' } });
    const login = await request(app).post('/api/v1/auth/login').send({ email: account.email, password: 'SecurePass123' }).expect(200);
    const bearer = `Bearer ${login.body.data.tokens.accessToken}`;
    const list = await request(app).get('/api/v1/admin/privacy-requests').set('Authorization', bearer).expect(200);
    const item = list.body.data.items[0];
    await request(app).put(`/api/v1/admin/privacy-requests/${item._id}/review`).set('Authorization', bearer).send({ reviewNotes: 'bad', nextReviewAt: new Date().toISOString() }).expect(400);
    await request(app).put(`/api/v1/admin/privacy-requests/${item._id}/review`).set('Authorization', bearer).send({ revision: item.revision ?? 0, reviewNotes: 'Pending financial retention and Cloudinary deletion evidence from the privacy reviewer.', nextReviewAt: new Date(Date.now() + 86400000).toISOString() }).expect(200);
    await UserModel.updateOne({ _id: account.user.id }, { $set: { role: 'user' } });
    await request(app).get('/api/v1/admin/privacy-requests').set('Authorization', bearer).expect(403);
  });
});
