import { randomUUID } from 'node:crypto';
import { beforeAll, afterAll, it, expect } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import { SubscriptionTier, SUBSCRIPTION_PLANS, VerificationLevel } from '@ubuntu-fund/types';
import { createTestApp } from '../helpers/testApp.js';
import { connectTestDatabase, disconnectTestDatabase, dropTestDatabase } from '../helpers/testDatabase.js';
import { UserModel } from '../../src/infrastructure/database/models/UserModel.js';
import { SubscriptionPlanModel } from '../../src/infrastructure/database/models/SubscriptionPlanModel.js';
import { SubscriptionModel } from '../../src/infrastructure/database/models/SubscriptionModel.js';
process.env.SPLIT_PROCEEDS_ENABLED = 'true';
let app: Express;
beforeAll(async () => { await connectTestDatabase(); app = await createTestApp(); });
afterAll(async () => { await dropTestDatabase(); await disconnectTestDatabase(); });
it('uses live plan caps for form options and POST, rejects expired privileges, and gates split/invites', async () => {
  const registration = await request(app).post('/api/v1/auth/register').send({ email: `campaign-${randomUUID()}@example.com`, name: 'Creator', password: 'SecurePass123' }).expect(201);
  const token = registration.body.data.tokens.accessToken;
  const userId = registration.body.data.user.id;
  const unverified = await request(app).get('/api/v1/campaigns/creation-options').set('Authorization', `Bearer ${token}`).expect(200);
  expect(unverified.body.data).toMatchObject({ activeCount: 0, totalCount: 0, canCreate: false, creationBlockReason: 'verification_required' });
  await UserModel.findByIdAndUpdate(userId, { verificationLevel: VerificationLevel.NATIONAL_ID });
  await SubscriptionPlanModel.findOneAndUpdate({ tier: SubscriptionTier.FREE }, { ...SUBSCRIPTION_PLANS[SubscriptionTier.FREE], maxCampaignGoal: 500, maxMediaPerCampaign: 1 }, { upsert: true });
  const options = await request(app).get('/api/v1/campaigns/creation-options').set('Authorization', `Bearer ${token}`).expect(200);
  expect(options.body.data.maxGoal).toBe(500);
  expect(options.body.data).toMatchObject({ canCreate: true, creationBlockReason: null });
  expect(options.body.data.canSplit).toBe(false);
  const input = { title: 'A community campaign', description: 'Helping the local community with supplies', goalAmount: 501, currency: 'GHS', category: 'education', priority: 'normal', beneficiaries: ['Community'], endDate: new Date(Date.now() + 86400000 * 30).toISOString() };
  const post = (body: object) => request(app).post('/api/v1/campaigns').set('Authorization', `Bearer ${token}`).send(body);
  await post(input).expect(422);
  await SubscriptionModel.findOneAndUpdate({ userId }, { userId, tier: SubscriptionTier.PRO, status: 'active', billingCycle: 'monthly', currentPeriodStart: new Date(Date.now() - 86400000 * 40), currentPeriodEnd: new Date(Date.now() - 1) }, { upsert: true });
  await post(input).expect(422);
  await post({ ...input, goalAmount: 500, imageUrls: ['https://example.com/a.jpg', 'https://example.com/b.jpg'] }).expect(422);
  const created = await post({ ...input, goalAmount: 500 }).expect(201);
  const campaignId = created.body.data.id;
  const fullPlan = await request(app).get('/api/v1/campaigns/creation-options').set('Authorization', `Bearer ${token}`).expect(200);
  expect(fullPlan.body.data).toMatchObject({ activeCount: 1, canCreate: false, creationBlockReason: 'plan_limit' });
  await post({ ...input, goalAmount: 100 }).expect(403);
  await request(app).post(`/api/v1/campaigns/${campaignId}/collaborators/invite`).set('Authorization', `Bearer ${token}`).send({ userEmail: 'person@example.com', role: 'editor', revenueSharePercent: 0 }).expect(403);
  const allocations = [{ name: 'One', email: 'one@example.com', shareBps: 5000 }, { name: 'Two', email: 'two@example.com', shareBps: 5000 }];
  await request(app).post(`/api/v1/campaigns/${campaignId}/split`).set('Authorization', `Bearer ${token}`).send({ allocations }).expect(403);
  await SubscriptionModel.findOneAndUpdate({ userId }, { currentPeriodEnd: new Date(Date.now() + 86400000 * 30) });
  await request(app).post(`/api/v1/campaigns/${campaignId}/split`).set('Authorization', `Bearer ${token}`).send({ allocations }).expect(201);
});
