import { DonationIntentModel } from '../../src/infrastructure/database/models/DonationIntentModel.js';
import { JournalEntryModel } from '../../src/infrastructure/database/models/JournalEntryModel.js';
import { randomUUID } from 'node:crypto';
import { beforeAll, afterAll, expect, it } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import { createTestApp } from '../helpers/testApp.js';
import { connectTestDatabase, disconnectTestDatabase, dropTestDatabase } from '../helpers/testDatabase.js';
import { DonationModel } from '../../src/infrastructure/database/models/DonationModel.js';
import { CampaignModel } from '../../src/infrastructure/database/models/CampaignModel.js';
import { UserModel } from '../../src/infrastructure/database/models/UserModel.js';
import { MongoDonationRepository } from '../../src/infrastructure/adapters/outbound/persistence/MongoDonationRepository.js';
let app: Express;
beforeAll(async () => { await connectTestDatabase(); app = await createTestApp(); });
afterAll(async () => { await dropTestDatabase(); await disconnectTestDatabase(); });
it('withholds unreviewed attribution, preserves private donor history and binds approved publication to its snapshot', async () => {
  const registration = await request(app).post('/api/v1/auth/register').send({ email: `${randomUUID()}@example.com`, password: 'SecurePass123', name: 'Account identity', legalAcceptance: { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true } }).expect(201);
  const id = registration.body.data.user.id, auth = `Bearer ${registration.body.data.tokens.accessToken}`;
  const campaign = await CampaignModel.create({ title: 'Attribution fixture', description: 'Testing public attribution', goalAmount: 1000, raisedAmount: 25, currency: 'GHS', category: 'education', status: 'active', creatorId: id, startDate: new Date(), endDate: new Date(Date.now() + 86400000) });
  const donation = await DonationModel.create({ campaignId: campaign.id, donorId: id, donorName: 'Submitted alias', message: 'Submitted message', amount: 25, currency: 'GHS', isAnonymous: false });
  const intent = await DonationIntentModel.create({ campaignId: campaign.id, donorUserId: id, donorName: 'Submitted alias', donorEmail: 'private@example.com', message: 'Submitted message', amount: 25, currency: 'GHS', tip: 0, isAnonymous: false, status: 'SUCCEEDED', provider: 'paystack', providerRef: randomUUID(), idempotencyKey: randomUUID() });
  const entry = await JournalEntryModel.create({ donationIntentId: intent.id, donationId: donation.id, memo: 'Review linkage fixture', currency: 'GHS' });
  const status = async () => {
    const response = await request(app).get(`/api/v1/donation-intents/${intent.id}/public`).expect(200);
    expect(response.headers['cache-control']).toContain('no-store');
    expect(JSON.stringify(response.body.data)).not.toMatch(/Submitted alias|Submitted message|private@example|Reviewed this donor/);
    expect(response.body.data).not.toHaveProperty('idempotencyKey');
    return response.body.data;
  };
  expect(await status()).toMatchObject({ status: 'SUCCEEDED', amount: 25, contentReviewStatus: 'pending' });
  await request(app).post(`/api/v1/donation-intents/${intent.id}/verify`).send({ reference: 'wrong-reference' }).expect(404);
  const recent = async () => (await request(app).get('/api/v1/donations').expect(200)).body.data;
  const initial = await recent();
  expect(JSON.stringify(initial)).not.toContain('Submitted alias');
  expect(JSON.stringify(initial)).not.toContain('Account identity');
  expect(initial[0]).toMatchObject({ amount: 25, isAnonymous: true });
  expect(initial[0].donorId).toBeUndefined();
  const privateView = (await request(app).get(`/api/v1/donations/${donation.id}`).set('Authorization', auth).expect(200)).body.data;
  expect(privateView.message).toBe('Submitted message');
  const staffAccount = await request(app).post('/api/v1/auth/register').send({ email: `${randomUUID()}@example.com`, password: 'SecurePass123', name: 'Staff reviewer', legalAcceptance: { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true } }).expect(201);
  const staffId = staffAccount.body.data.user.id, staffAuth = `Bearer ${staffAccount.body.data.tokens.accessToken}`;
  await UserModel.updateOne({ _id: staffId }, { $set: { role: 'admin' } });
  const path = '/api/v1/admin/donation-content-reviews';
  await request(app).get(path).expect(401);
  await request(app).get(path).set('Authorization', auth).expect(403);
  const queue = (await request(app).get(path).set('Authorization', staffAuth).expect(200)).body.data;
  const item = queue.items.find((row: { id: string }) => row.id === donation.id);
  expect(JSON.stringify(queue)).not.toContain('private@example.com');
  const actions = (await request(app).get('/api/v1/admin/action-center').set('Authorization', staffAuth).expect(200)).body.data.items;
  expect(actions.find((row: { id: string }) => row.id === 'donation-content-reviews')).toMatchObject({ count: 1, href: '/publication-reviews?queue=donation-content-reviews' });
  await request(app).put(`${path}/${donation.id}/review`).set('Authorization', staffAuth).send({ version: '0'.repeat(64), decision: 'approved', notes: 'Reviewed this donor name and message in full.' }).expect(409);
  await request(app).put(`${path}/${donation.id}/review`).set('Authorization', staffAuth).send({ version: item.version, decision: 'approved', notes: 'Reviewed this donor name and message in full.' }).expect(200);
  expect((await recent())[0]).toMatchObject({ donorName: 'Submitted alias', amount: 25, isAnonymous: false });
  expect((await status()).contentReviewStatus).toBe('approved');
  const verified = await request(app).post(`/api/v1/donation-intents/${intent.id}/verify`).send({ reference: intent.providerRef }).expect(200);
  expect(verified.body.data.contentReviewStatus).toBe('approved');
  expect(verified.headers['cache-control']).toContain('no-store');
  await UserModel.updateOne({ _id: id }, { $set: { name: 'Later profile name' } });
  expect((await recent())[0].donorName).toBe('Submitted alias');
  const repo = new MongoDonationRepository();
  expect((await repo.findById(donation.id))?.publicMessage).toBe('Submitted message');
  await DonationModel.updateOne({ _id: donation.id }, { $set: { message: 'Unreviewed replacement' } });
  expect((await repo.findById(donation.id))?.publicMessage).toBeUndefined();
  expect((await recent())[0].donorName).toBeUndefined();
  expect((await CampaignModel.findById(campaign.id))?.raisedAmount).toBe(25);
  expect((await DonationModel.findById(donation.id))?.amount).toBe(25);
  expect((await status()).contentReviewStatus).toBe('pending');
  await DonationModel.updateOne({ _id: donation.id }, { $set: { publicContentRevokedAt: new Date() } });
  expect((await status()).contentReviewStatus).toBe('not_requested');
  await JournalEntryModel.deleteOne({ _id: entry.id });
  expect(await status()).toMatchObject({ status: 'SUCCEEDED', amount: 25, contentReviewStatus: 'unavailable' });
});
