import { createReviewedDonation } from '../helpers/reviewedDonation.js';
import { createReviewedTip } from '../helpers/reviewedTip.js';
import { randomUUID } from 'node:crypto';
import { beforeAll, afterAll, it, expect, vi } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import { createTestApp } from '../helpers/testApp.js';
import { connectTestDatabase, disconnectTestDatabase, dropTestDatabase } from '../helpers/testDatabase.js';
import { UserModel } from '../../src/infrastructure/database/models/UserModel.js';
import { DonationModel } from '../../src/infrastructure/database/models/DonationModel.js';
import { TipModel } from '../../src/infrastructure/database/models/TipModel.js';
import { CreatorProfileModel } from '../../src/infrastructure/database/models/CreatorProfileModel.js';
import { SafetyReportModel } from '../../src/infrastructure/database/models/SafetyReportModel.js';
import { MongoDonationRepository } from '../../src/infrastructure/adapters/outbound/persistence/MongoDonationRepository.js';
import { OutboxDispatcher } from '../../src/application/services/OutboxDispatcher.js';
import type { OutboxRepositoryPort } from '../../src/domain/ports/outbound/OutboxRepositoryPort.js';
import type { RealtimeDonationProjector } from '../../src/application/services/RealtimeDonationProjector.js';
import type { OutboxRecord } from '@ubuntu-fund/types';
let app: Express;
beforeAll(async () => { await connectTestDatabase(); app = await createTestApp(); await SafetyReportModel.init(); });
afterAll(async () => { await dropTestDatabase(); await disconnectTestDatabase(); });
async function user() {
  const r = await request(app).post('/api/v1/auth/register').send({ name: 'Message review', email: `${randomUUID()}@example.test`, password: 'SecurePass123', legalAcceptance: { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true } }).expect(201);
  return { id: r.body.data.user.id, token: `Bearer ${r.body.data.tokens.accessToken}` };
}
it('hides a guest donation message without changing money, preserves private evidence and suppresses stale outbox text', async () => {
  const reporter = await user(), admin = await user(); await UserModel.findByIdAndUpdate(admin.id, { role: 'admin' });
  const donation = await createReviewedDonation({ campaignId: 'aaaaaaaaaaaaaaaaaaaaaaaa', donorId: 'guest', amount: 75, currency: 'GHS', message: 'Message requiring moderation', isAnonymous: true });
  const input = { targetType: 'donation_message', targetId: donation.id, reason: 'harassment', description: 'Please review this public donation message.' };
  await request(app).post('/api/v1/safety/reports').send(input).expect(401);
  const report = await request(app).post('/api/v1/safety/reports').set('Authorization', reporter.token).send(input).expect(201);
  expect(report.body.data).not.toHaveProperty('targetUserId');
  const stored = await SafetyReportModel.findById(report.body.data.id);
  expect(stored?.targetUserId).toBeUndefined(); expect(stored?.evidence).toBe(donation.message);
  const path = `/api/v1/admin/safety-reports/${report.body.data.id}/review`;
  await request(app).put(path).set('Authorization', admin.token).send({ action: 'restrict_user', notes: 'There is no verified guest account to restrict.' }).expect(400);
  await request(app).put(path).set('Authorization', admin.token).send({ action: 'hide_message', notes: 'Reviewed and hidden the abusive public message.' }).expect(200);
  const current = await DonationModel.findById(donation.id);
  expect(current?.message).toBeUndefined(); expect(current?.messageHiddenAt).toBeInstanceOf(Date); expect(current?.amount).toBe(75);
  expect(await new MongoDonationRepository().updateMessage(donation.id, 'guest', 'Attempt to restore hidden text', { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true, acceptedAt: new Date() })).toBeNull();
  const recordDonationRealtime = vi.fn(), markDispatched = vi.fn(), recordAttempt = vi.fn();
  const dispatcher = new OutboxDispatcher({ markDispatched, recordAttempt } as unknown as OutboxRepositoryPort, { recordDonationRealtime } as unknown as RealtimeDonationProjector, new MongoDonationRepository());
  await dispatcher.dispatch({ id: 'outbox-test', type: 'donation.succeeded', status: 'pending', payload: { donationId: donation.id, campaignId: donation.campaignId, donorId: 'guest', donorName: 'Private name', amount: 75, currency: 'GHS', message: donation.message, isAnonymous: false, createdAt: new Date().toISOString() } } as OutboxRecord);
  expect(recordDonationRealtime.mock.calls[0][2]).toMatchObject({ amount: 75, message: undefined, donorName: undefined, isAnonymous: true });
  expect(markDispatched).toHaveBeenCalled(); expect(recordAttempt).not.toHaveBeenCalled();
});
it.each([true, false])('removes a tip message and requeues remaining attribution (anonymous=%s)', async isAnonymous => {
  const reporter = await user(), owner = await user(), supporter = await user(), admin = await user(); await UserModel.findByIdAndUpdate(admin.id, { role: 'admin' });
  const handle = `report-${randomUUID().slice(0, 8)}`;
  await CreatorProfileModel.create({ userId: owner.id, handle, displayName: 'Creator' });
  const tip = await createReviewedTip({ creatorUserId: owner.id, supporterUserId: supporter.id, supporterEmail: 'private@example.test', supporterName: 'Private supporter', amount: 50, currency: 'GHS', platformFee: 0, netAmount: 50, status: 'SUCCEEDED', settlementApplied: true, provider: 'paystack', providerRef: randomUUID(), message: 'Message to review', isAnonymous });
  const before = await request(app).get(`/api/v1/creators/${handle}`).expect(200);
  expect(before.body.data.recentTips[0]).toMatchObject({ id: tip.id, supporterName: isAnonymous ? 'Anonymous' : 'Private supporter' });
  expect(JSON.stringify(before.body)).not.toContain('private@example.test'); expect(JSON.stringify(before.body)).not.toContain(supporter.id);
  const input = { targetType: 'tip_message', targetId: tip.id, reason: 'spam', description: 'Please review the message on this support.' };
  await request(app).post('/api/v1/safety/reports').set('Authorization', supporter.token).send(input).expect(400);
  const report = await request(app).post('/api/v1/safety/reports').set('Authorization', reporter.token).send(input).expect(201);
  await request(app).put(`/api/v1/admin/safety-reports/${report.body.data.id}/review`).set('Authorization', admin.token).send({ action: 'hide_message', notes: 'Reviewed and removed the spam supporter message.' }).expect(200);
  const after = await request(app).get(`/api/v1/creators/${handle}`).expect(200);
  expect(after.body.data.recentTips[0].message).toBeUndefined(); expect(after.body.data.supporterCount).toBe(before.body.data.supporterCount); expect(after.body.data.totalReceived).toBe(50);
  const stored = await TipModel.findById(tip.id);
  expect(stored?.amount).toBe(50);
  expect(stored?.publicContentStatus).toBe('pending');
  expect(stored?.publicContentFingerprint).toBeUndefined();
  const queue = (await request(app).get('/api/v1/admin/tip-content-reviews').set('Authorization', admin.token).expect(200)).body.data.items;
  const item = queue.find((row: { id: string }) => row.id === tip.id);
  if (isAnonymous) expect(item).toBeUndefined();
  else {
    expect(item.status).toBe('pending');
    expect(item.text).not.toContain('Message to review');
    const path = `/api/v1/admin/tip-content-reviews/${tip.id}/review`;
    const input = { decision: 'approved', notes: 'Reviewed the remaining public supporter name.' };
    await request(app).put(path).set('Authorization', admin.token).send({ ...input, version: tip.publicContentFingerprint }).expect(409);
    await request(app).put(path).set('Authorization', admin.token).send({ ...input, version: item.version }).expect(200);
    const reviewed = (await request(app).get(`/api/v1/creators/${handle}`).expect(200)).body.data;
    expect(reviewed.recentTips[0]).toMatchObject({ supporterName: 'Private supporter', amount: 50 });
    expect(reviewed.recentTips[0].message).toBeUndefined();
    expect((await TipModel.findById(tip.id))?.messageHiddenAt).toBeInstanceOf(Date);
  }
});
