import { randomUUID } from 'node:crypto';
import { beforeAll, afterAll, expect, it, vi } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import { createTestApp } from '../helpers/testApp.js';
import { connectTestDatabase, disconnectTestDatabase, dropTestDatabase } from '../helpers/testDatabase.js';
import { CreatorProfileModel } from '../../src/infrastructure/database/models/CreatorProfileModel.js';
import { TipModel } from '../../src/infrastructure/database/models/TipModel.js';
import { PaystackGateway } from '../../src/infrastructure/adapters/outbound/payments/PaystackGateway.js';
import { PlanLimitsService } from '../../src/application/services/PlanLimitsService.js';
let app: Express;
const initialize = vi.spyOn(PaystackGateway.prototype, 'initializeCharge').mockImplementation(async input => ({ reference: input.reference!, authorizationUrl: 'https://checkout.paystack.com/fixture', accessCode: 'fixture' }));
beforeAll(async () => {
  await connectTestDatabase();
  vi.spyOn(PlanLimitsService.prototype, 'assertCreatorDonations').mockResolvedValue();
  app = await createTestApp();
  await TipModel.init();
});
afterAll(async () => { vi.restoreAllMocks(); await dropTestDatabase(); await disconnectTestDatabase(); });
it('honors the request header through middleware, persists one attempt and confirms terminal retries', async () => {
  const registered = await request(app).post('/api/v1/auth/register').send({ email: `${randomUUID()}@example.com`, password: 'SecurePass123', name: 'HTTP fixture', legalAcceptance: { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true } }).expect(201);
  const owner = registered.body.data.user.id;
  await CreatorProfileModel.create({ userId: owner, handle: 'http-checkout', displayName: 'HTTP Creator', tipsEnabled: true });
  const path = '/api/v1/creators/http-checkout/tips';
  const payload = { amount: 25, supporterEmail: 'fixture@example.com' };
  await request(app).post(path).set('Idempotency-Key', 'bad').send(payload).expect(400);
  expect(initialize).not.toHaveBeenCalled();
  const first = await request(app).post(path).set('Idempotency-Key', 'http-checkout-attempt').send(payload).expect(201);
  expect(first.headers['cache-control']).toBe('private, no-store');
  const retry = await request(app).post(path).set('Idempotency-Key', 'http-checkout-attempt').send(payload).expect(201);
  expect(retry.body.data).toEqual(first.body.data);
  await request(app).post(path).set('Idempotency-Key', 'http-checkout-attempt').send({ ...payload, amount: 30 }).expect(409);
  expect(await TipModel.countDocuments({ creatorUserId: owner })).toBe(1);
  expect(initialize).toHaveBeenCalledTimes(1);
  await TipModel.updateOne({ providerRef: first.body.data.reference }, { $set: { status: 'SUCCEEDED', settlementApplied: true }, $unset: { checkout: 1 } });
  const terminal = await request(app).post(path).set('Idempotency-Key', 'http-checkout-attempt').send(payload).expect(201);
  expect(terminal.body.data.checkoutUrl).toBe(`/tip/callback?reference=${first.body.data.reference}`);
  expect(terminal.body.data.accessCode).toBe('');
  expect(initialize).toHaveBeenCalledTimes(1);
});
