import { test, expect } from '@playwright/test'
test('reports an AI suggestion inside the campaign wizard at phone width', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => {
    localStorage.setItem('uf_user', JSON.stringify({ id: 'aaaaaaaaaaaaaaaaaaaaaaaa', name: 'Creator', role: 'user', legalAcceptance: { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true, acceptedAt: '2026-09-12T00:00:00Z' } }))
    localStorage.setItem('uf_tokens', JSON.stringify({ accessToken: 'test', refreshToken: 'test' }))
  })
  await page.route('**/api/v1/**', route => route.fulfill({ json: { data: route.request().url().endsWith('/auth/refresh') ? { accessToken: 'test', refreshToken: 'test' } : [] } }))
  await page.route('**/api/v1/notifications/unread-count', route => route.fulfill({ json: { data: { count: 0 } } }))
  await page.route('**/api/v1/campaigns/creation-options', route => route.fulfill({ json: { data: { plan: { name: 'Test', maxCampaignGoal: -1 }, maxGoal: null, activeCount: 0, canCreate: true, canSplit: false, splitEnabled: false } } }))
  await page.route('**/api/v1/ai-writing/config', route => route.fulfill({ json: { data: { enabled: true, remainingRequests: 20, dailyLimit: 20 } } }))
  await page.route('**/api/v1/ai-writing', route => route.fulfill({ json: { data: { requestId: 'bbbbbbbbbbbbbbbbbbbbbbbb', result: 'A generated suggestion to review.', remainingRequests: 19 } } }))
  let report: unknown
  await page.route('**/api/v1/safety/reports', route => { report = route.request().postDataJSON(); return route.fulfill({ json: { data: { id: 'report', status: 'pending' } } }) })
  await page.goto('/campaigns/new')
  await page.getByRole('textbox', { name: 'Campaign title', exact: true }).fill('Community library')
  await page.getByRole('group', { name: 'Category', exact: true }).getByRole('button').first().click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('textbox', { name: 'Your story', exact: true }).fill('We are raising funds to create a library for our community.')
  await page.getByRole('checkbox', { name: /I agree to send/ }).check()
  await page.getByRole('button', { name: 'Get suggestion', exact: true }).click()
  await expect(page.getByText('A generated suggestion to review.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Report', exact: true }).click()
  await page.getByRole('textbox', { name: 'What happened?' }).fill('Please review the safety of this generated suggestion.')
  await page.getByRole('button', { name: 'Send report', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Report received')
  expect(report).toMatchObject({ targetType: 'ai_output', targetId: 'bbbbbbbbbbbbbbbbbbbbbbbb', generatedText: 'A generated suggestion to review.' })
  await page.getByRole('status').scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/ujimora-ai-report-phone.png', animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
