import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
test('optional MFA setup and branded QR lead to copyable and downloadable recovery codes at phone width', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.addInitScript(() => {
    localStorage.setItem('uf_user', JSON.stringify({ id: 'mfa-user', name: 'Ama', email: 'ama@example.test', role: 'user', legalAcceptance: { version: '2026-09-12', acceptedTerms: true, ageConfirmed: true } }))
    localStorage.setItem('uf_tokens', JSON.stringify({ accessToken: 'test', refreshToken: 'test' }))
  })
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.route('**/api/v1/**', route => route.fulfill({ json: { data: route.request().url().endsWith('/auth/refresh') ? { accessToken: 'test', refreshToken: 'test' } : [] } }))
  await page.route('**/api/v1/notifications/unread-count', route => route.fulfill({ json: { data: { count: 0 } } }))
  await page.route('**/api/v1/auth/mfa', route => route.fulfill({ json: { data: { available: true, enabled: false, recoveryCodesRemaining: 0 } } }))
  await page.route('**/api/v1/newsletter/preference', route => route.fulfill({ json: { data: { status: 'off' } } }))
  await page.route('**/api/v1/profile/activity-alerts', route => route.fulfill({ json: { data: { emailVerified: false, emailConfigured: false, preferences: Object.fromEntries(['donationsReceived', 'donationsSent', 'creatorTips', 'withdrawals', 'refunds', 'wallet', 'subscriptions'].map(category => [category, { inApp: false, email: false }])) } } }))
  for (const path of ['publication-reviews**', 'data-rights**', 'safety/blocks']) await page.route(`**/api/v1/${path}`, route => route.fulfill({ json: { data: { items: [], total: 0 } } }))
  await page.route('**/api/v1/profile', route => route.fulfill({ json: { data: { id: 'mfa-user', name: 'Ama', settings: {} } } }))
  // A real locally generated QR of a non-secret test account URI, never an external QR service.
  const QRCode = await import('qrcode')
  const qrCode = await QRCode.toDataURL('otpauth://totp/Ujimora:test?secret=JBSWY3DPEHPK3PXP&issuer=Ujimora')
  await page.route('**/api/v1/auth/mfa/setup', route => route.fulfill({ json: { data: { enrollmentId: 'test-setup', secret: 'JBSWY3DPEHPK3PXP', qrCode } } }))
  const codes = ['abcd-1234-5678-9012-abcd-1234-5678-9012', 'dcba-4321-8765-2109-dcba-4321-8765-2109']
  await page.route('**/api/v1/auth/mfa/enable', route => {
    expect(route.request().postDataJSON()).toMatchObject({ code: '123456', enrollmentId: 'test-setup' })
    return route.fulfill({ json: { data: { tokens: { accessToken: 'new', refreshToken: 'new' }, recoveryCodes: codes } } })
  })
  await page.goto('/settings')
  const section = page.getByRole('region', { name: 'Authenticator protection' })
  await section.getByLabel('Current password').fill('TestPassword123')
  await section.getByRole('button', { name: 'Set up authenticator' }).click()
  await expect(section.getByAltText('QR code to add Ujimora to your authenticator')).toBeVisible()
  await section.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/ujimora-mfa-setup-phone.png' })
  for (let index = 1; index <= 6; index++) await section.getByLabel(`Digit ${index}`).fill(String(index))
  await section.getByRole('button', { name: 'Confirm and enable MFA' }).click()
  await section.getByRole('button', { name: 'Copy recovery codes' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(codes.join('\n'))
  const downloaded = page.waitForEvent('download')
  await section.getByRole('button', { name: 'Download recovery codes' }).click()
  const download = await downloaded
  expect(download.suggestedFilename()).toBe('ujimora-recovery-codes.txt')
  expect(await readFile((await download.path())!, 'utf8')).toContain(codes.join('\n'))
  await section.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/ujimora-mfa-recovery-phone.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  expect(errors).toEqual([])
})

test('keeps sign-in unauthenticated until the required authenticator code is submitted', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const submissions: Record<string, string>[] = []
  await page.route('**/api/v1/auth/login', route => {
    submissions.push(route.request().postDataJSON())
    return route.fulfill({ status: 401, json: { message: 'Enter a valid authenticator code or an unused recovery code.' } })
  })
  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('ama@example.test')
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('TestPassword123')
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect(page.getByLabel('Digit 1')).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('uf_tokens'))).toBeNull()
  for (let index = 1; index <= 6; index++) await page.getByLabel(`Digit ${index}`).fill(String(index))
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect.poll(() => submissions.length).toBe(2)
  expect(submissions[1].mfaCode).toBe('123456')
  expect(await page.evaluate(() => localStorage.getItem('uf_tokens'))).toBeNull()
  await page.getByRole('button', { name: 'Use a recovery code' }).click()
  await expect(page.getByRole('textbox', { name: 'Recovery code', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
