import { createElement } from 'react'
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, expect, it, vi } from 'vitest'
import { PaymentStatus } from '../PaymentStatus'
import { api } from '@/lib/api'
const { appStateListeners } = vi.hoisted(() => ({ appStateListeners: new Set<(state: string) => void>() }))
vi.mock('react-native', () => ({ View: 'div', AppState: { currentState: 'active', addEventListener: (_event: string, listener: (state: string) => void) => { appStateListeners.add(listener); return { remove() { appStateListeners.delete(listener) } } } } }))
vi.mock('react-native-paper', () => ({ Text: 'span' }))
vi.mock('expo-web-browser', () => ({ openBrowserAsync: vi.fn() }))
vi.mock('../DonationCelebration', () => ({ DonationCelebration: () => null }))
vi.mock('../Loading', () => ({ Skeleton: () => null, Button: ({ children, onPress, disabled }: { children: string; onPress: () => void; disabled?: boolean }) => createElement('button', { onClick: onPress, disabled }, children) }))
vi.mock('@/context/ColorModeContext', () => ({ usePalette: () => ({}), useNeu: () => ({ raised: {} }) }))
vi.mock('@/lib/payments', () => {
  const isPaymentSuccess = (status: string) => ['SUCCEEDED', 'completed'].includes(status)
  const isPaymentTerminal = (status: string) => isPaymentSuccess(status) || ['FAILED', 'EXPIRED', 'failed'].includes(status)
  return { isPaymentSuccess, isPaymentTerminal, canStartOver: (status: string, startedAt: number, now = Date.now()) => !isPaymentTerminal(status) && now - startedAt >= 15 * 60 * 1000 }
})
beforeEach(() => vi.clearAllMocks())
const payment = (id: string, status = 'SUCCEEDED') => ({ id, status, storageKey: '' })
it('reads review status for an already settled wallet donation and retains success on refresh failure', async () => {
  vi.mocked(api.get).mockResolvedValueOnce({ status: 'SUCCEEDED', contentReviewStatus: 'pending' })
  const completed = vi.fn()
  render(createElement(PaymentStatus, { payment: payment('first'), onComplete: completed, onReset() {} }))
  expect(await screen.findByText(/awaiting review/)).toBeTruthy()
  vi.mocked(api.get).mockRejectedValueOnce(new Error('offline'))
  fireEvent.click(screen.getByText('Refresh content review'))
  expect(await screen.findByText('offline')).toBeTruthy()
  expect(screen.queryByText(/awaiting review/)).toBeNull()
  expect(screen.getByText('Thank you for your support')).toBeTruthy()
  vi.mocked(api.get).mockResolvedValueOnce({ status: 'SUCCEEDED', contentReviewStatus: 'approved' })
  fireEvent.click(screen.getByText('Refresh content review'))
  expect(await screen.findByText(/has been approved/)).toBeTruthy()
  expect(completed).toHaveBeenCalledTimes(1)
  expect(api.post).not.toHaveBeenCalled()
})
it('discards a previous payment response after switching targets without caller keys', async () => {
  let finish!: (value: unknown) => void
  vi.mocked(api.get).mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
  const view = render(createElement(PaymentStatus, { payment: payment('first', 'PENDING'), onReset() {} }))
  vi.mocked(api.get).mockResolvedValue({ status: 'SUCCEEDED', contentReviewStatus: 'rejected' })
  view.rerender(createElement(PaymentStatus, { payment: payment('second'), onReset() {} }))
  expect(await screen.findByText(/was not approved/)).toBeTruthy()
  await act(async () => finish({ status: 'SUCCEEDED', contentReviewStatus: 'approved' }))
  expect(screen.queryByText(/has been approved/)).toBeNull()
  expect(screen.getByText('Reference: second')).toBeTruthy()
  await waitFor(() => expect(api.get).toHaveBeenCalledWith('/donation-intents/second/public'))
})
it('offers a fresh checkout once an unconfirmed payment is stale, and not before (I038)', async () => {
  vi.mocked(api.post).mockResolvedValue({ status: 'PENDING' })
  const reset = vi.fn()
  const fresh = render(createElement(PaymentStatus, { payment: { ...payment('fresh', 'PENDING'), reference: 'uf-fresh', createdAt: Date.now() }, onReset: reset }))
  await waitFor(() => expect(api.post).toHaveBeenCalled())
  expect(screen.queryByText('Start a new payment')).toBeNull()
  fresh.unmount()
  render(createElement(PaymentStatus, { payment: { ...payment('stale', 'PENDING'), reference: 'uf-stale', createdAt: Date.now() - 16 * 60 * 1000 }, onReset: reset }))
  fireEvent.click(await screen.findByText('Start a new payment'))
  expect(screen.getByText(/don't pay again/)).toBeTruthy()
  expect(reset).toHaveBeenCalledTimes(1)
})
it('re-checks a recently failed top-up when the payer returns to the app (I039)', async () => {
  vi.mocked(api.get).mockResolvedValue({ status: 'failed' })
  render(createElement(PaymentStatus, { payment: { ...payment('wtop-1', 'failed'), createdAt: Date.now() }, topup: true, onReset() {} }))
  await waitFor(() => expect(api.get).toHaveBeenCalledTimes(1))
  expect(appStateListeners.size).toBe(1)
  vi.mocked(api.get).mockResolvedValue({ status: 'completed' })
  await act(async () => { for (const listener of appStateListeners) listener('active') })
  await waitFor(() => expect(api.get).toHaveBeenCalledTimes(2))
  expect(api.get).toHaveBeenLastCalledWith('/wallets/topups/wtop-1')
})
